<?php
/**
 * @file
 * Code for the Core feature.
 */

include_once 'barony_core.features.inc';

/**
 * Implements hook_ctools_plugin_directory().
 */
function barony_core_ctools_plugin_directory($module, $plugin) {
  return 'plugins/' . $plugin;
}

/**
 * Implements hook_entity_info_alter().
 */
function barony_core_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['summary'] = array(
    'label' => t('Summary'),
    'custom settings' => TRUE,
  );
  $entity_info['node']['view modes']['main_page_left'] = array(
    'label' => t('Main - Left'),
    'custom settings' => TRUE,
  );
  $entity_info['node']['view modes']['main_page_right'] = array(
    'label' => t('Main - Right'),
    'custom settings' => TRUE,
  );
}

/**
 * Implements hook_preprocess_page().
 */
function barony_core_preprocess_page(&$vars) {
  // Add Font Awesome
  // @todo - decide if we really need FA or if bootstrap glyphs are fine
  drupal_add_js('//use.fontawesome.com/76948938e9.js', 'external');
  // Add Google Fonts
  drupal_add_css('//fonts.googleapis.com/css?family=Uncial+Antiqua|Metamorphous', array('group' => CSS_THEME));
}