<?php
/**
 * @file
 * Code for the Core feature.
 */

include_once 'barony_core.features.inc';

/**
 * Implements hook_ctools_plugin_directory().
 */
function barony_core_ctools_plugin_directory($module, $plugin) {
  return 'plugins/' . $plugin;
}

/**
 * Implements hook_entity_info_alter().
 */
function barony_core_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['summary'] = array(
    'label' => t('Summary'),
    'custom settings' => TRUE,
  );
  $entity_info['node']['view modes']['main_page_left'] = array(
    'label' => t('Main - Left'),
    'custom settings' => TRUE,
  );
  $entity_info['node']['view modes']['main_page_right'] = array(
    'label' => t('Main - Right'),
    'custom settings' => TRUE,
  );
}

/**
 * Implements hook_preprocess_page().
 */
function barony_core_preprocess_page(&$vars) {
  // Add in js related to plugins in this module
  drupal_add_js(drupal_get_path('module', 'barony_core') . '/js/highlight-flipper.js', array('type' => 'file', 'scope' => 'footer'));
}

